cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 40000
  ladW2: 30000
  mesh: 2
  nfmin: 20
  nfrad: 5
  wd: 0
picker:
  azimuth:
    max: 20
    min: 0
  fitness:
    max: 1
    min: 0.65
  rmse:
    max: 5
    min: 0
  rotation:
    max: 180
    min: -180
  transX:
    max: 3000
    min: -3000
  transY:
    max: 3000
    min: -3000
rovi:
  pshift_genpc:
    calc:
      bw_diff: 8
      darkness: 5
  ycam:
    ExposureTimeLevel: 2
    camera:
      Gain: 0
    projector:
      Intensity: 200
    hdr:
      enabled: true
      pcgen_publish: false
      projector:
        Intensity: 0.2
searcher:
  distance_threshold: 10
  feature_mesh: 4
  feature_radius: 18
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 8
  repeat: 1
  rotate: 0

