cropper:
  cropR: 0.3
  cropR2: 0.08
  cropZ: 1.0
  ladC: 0
  ladW: 6000
  ladW2: 30000
  mesh: 0.001
  nfmin: 0
  nfrad: 0.005
picker:
  azimuth:
    max: 1
    min: 0
  fitness:
    max: 1
    min: 0.7
  rmse:
    max: 5
    min: 0
rovi:
  live:
    camera:
      ExposureTime: 300000
      Gain: 63
  pshift_genpc:
    camera:
      ExposureTime: 8400
      Gain: 0
    projector:
      Intencity: 150
      Mode: 1
searcher:
  distance_threshold: 0.1
  feature_mesh: 0.004
  feature_radius: 0.03
  icp_threshold: 0.005
  normal_min_nn: 0
  normal_radius: 0.01
  repeat: 5
  rotate: 0
